name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ensorflow-resnet:latest .
        docker tag ensorflow-resnet:latest ${{ secrets.DOCKER_USERNAME }}/ensorflow-resnet:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ensorflow-resnet:latest
